language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t okan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true okan/docker-react npm run test -- --coverage

deploy:
  provider: azure_web_apps
  verbose: true
  on:
    all_branches: true
  site: docker-react99.scm.azurewebsites.net
  username: $AZURE_USERNAME
  password: "$AZURE_PASSWORD"
